FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY . .
# Adding automatic library download before compilation
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/{{.ServiceName}}/main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/main .
EXPOSE {{.Port}}
CMD ["./main"]